### ISSUE TITLE
Game incorrectly sized

### ISSUE THREAD

**Issue by Basty7** [lukasz1985/SREM#1]
#Hey @lukasz1985 
I just wanted to tell you your game is very good, it only has two problems

1. The game regularly prints random things in the console
2. The game window isn't correctly sized (biggest problem in my POV)

Have a good time fixing these errors, I may help if you want/need.

**Comment by catlukemich** [comment]
I've fixed the prints, and made the window size fixed, so you can check it now.

**Comment by Basty7** [comment]
Thanks a lot for your game, sadly I still can't see my funds in landscape mode (it may be because of the very poor resolution of my screen which is 1366 x 768 px, didn't try on another display just to test).
Anyways, good job and have a nice journey coding your game !

**Comment by catlukemich** [comment]
There is now a popup window that allows to change the screen size before the game launches. It should do the job.
